peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))
imc = peso / (altura**2)
print(f"Seu imc total é igual a")
if imc >39.9: print(f"Seu imc deu {imc:.2f}, você esta com: Obesidade Grau III ")
elif imc >35: print(f"Seu imc deu {imc:.2f}, você esta com: Obesidade Grau II ")
elif imc >30: print(f"Seu imc deu {imc:.2f}, você esta com: Obesidade Grau I ")
elif imc >25: print(f"Seu imc deu {imc:.2f}, você esta com: Sobrepeso ")
elif imc >18.5: print(f"Seu imc deu {imc:.2f}, você esta com: Normal ")
elif imc <18.5: print(f"Seu imc deu {imc:.2f}, você esta com: Magreza ")
